name: stockx
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - aom=3.12.1
  - appdirs=1.4.4
  - arrow-cpp=21.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - beautifulsoup4=4.14.2
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cachetools=6.2.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - colorama=0.4.6
  - dav1d=1.2.1
  - entrypoints=0.4
  - expat=2.7.3
  - fontconfig=2.15.0
  - freeglut=3.8.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozendict=2.4.6
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.43
  - glog=0.5.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - html5lib=1.1
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.16.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libglib=2.84.4
  - libgrpc=1.71.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libmpdec=4.0.0
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=5.3.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - multitasking=0.0.12
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openssl=3.0.18
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - peewee=3.18.2
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - protobuf=5.29.3
  - pyarrow=21.0.0
  - pycparser=2.23
  - pydeck=0.9.1
  - pysocks=1.7.1
  - python=3.14.1
  - python-dateutil=2.9.0post0
  - python-dotenv=1.2.1
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - pyyaml=6.0.3
  - re2=2024.07.02
  - referencing=0.37.0
  - requests=2.32.5
  - rpds-py=0.28.0
  - six=1.17.0
  - smmap=4.0.0
  - snappy=1.2.1
  - soupsieve=2.5
  - sqlite=3.51.0
  - streamlit=1.52.1
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tenacity=9.1.2
  - tk=8.6.15
  - toml=0.10.2
  - toolz=1.1.0
  - tornado=6.5.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.6.0
  - utf8proc=2.6.1
  - vadersentiment=3.3.2
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchdog=6.0.0
  - webencodings=0.5.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - yfinance=0.2.57
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - gdeltdoc==1.12.0
prefix: C:\Users\LENOVO\anaconda3\envs\stockx
