name: stockx
channels:
  - conda-forge
  - dnachun
  - defaults
dependencies:
  - altair=4.1.0=py_1
  - aom=3.12.1=h00a0c3c_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow-cpp=21.0.0=h6358905_1
  - attrs=25.4.0=py314haa95532_2
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - beautifulsoup4=4.14.2=py314haa95532_0
  - blas=1.0=mkl
  - blinker=1.9.0=py314haa95532_1
  - bottleneck=1.4.2=py314h2b7f5b3_1
  - brotlicffi=1.2.0.0=py314h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.12.2=haa95532_0
  - cachetools=6.2.2=py314haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=py314haa95532_0
  - cffi=2.0.0=py314h02ab6af_1
  - charset-normalizer=3.4.4=py314haa95532_0
  - click=8.2.1=py314haa95532_1
  - cloudscraper=1.2.71=pyh4616a5c_0
  - colorama=0.4.6=py314haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - entrypoints=0.4=py314haa95532_0
  - expat=2.7.3=h885b0b7_4
  - fontconfig=2.15.0=hd211d86_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozendict=2.4.6=py314h02ab6af_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.12=py314haa95532_0
  - gitpython=3.1.43=py314haa95532_0
  - glog=0.5.0=hd77b12b_1
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=73.1=h6c2663c_0
  - idna=3.11=py314haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jinja2=3.1.6=py314haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py314haa95532_1
  - jsonschema-specifications=2025.9.1=py314haa95532_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.3.0=h5bd13ec_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libgrpc=1.71.0=hf4237ab_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libmpdec=4.0.0=h827c3e9_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.22.0=ha2884a9_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libxslt=1.1.43=hd1fac9c_0
  - libzlib=1.3.1=h02ab6af_0
  - lxml=5.3.0=py314h985e36a_2
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py314h827c3e9_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py314h0b37514_0
  - mkl_fft=2.1.1=py314h281c9fe_0
  - mkl_random=1.3.0=py314hdbada53_0
  - multitasking=0.0.12=py314haa95532_0
  - numexpr=2.14.1=py314h2592778_0
  - numpy=2.3.5=py314h0be4137_0
  - numpy-base=2.3.5=py314h96ad93d_0
  - openssl=3.0.18=h543e019_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py314haa95532_1
  - pandas=2.3.3=py314hdbada53_1
  - pcre2=10.46=h5740b90_0
  - peewee=3.18.2=py314h54f65d0_0
  - pillow=12.0.0=py314h4212202_1
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py314haa95532_0
  - protobuf=5.29.3=py314h5da7b33_0
  - pyarrow=21.0.0=py314hdbada53_1
  - pycparser=2.23=py314haa95532_0
  - pydeck=0.9.1=py314haa95532_0
  - pyparsing=3.2.5=py314haa95532_0
  - pysocks=1.7.1=py314haa95532_1
  - python=3.14.1=h3bc0a5a_101_cp314
  - python-dateutil=2.9.0post0=py314haa95532_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314haa95532_0
  - pyyaml=6.0.3=py314hb9a58be_0
  - re2=2024.07.02=h214f63a_0
  - referencing=0.37.0=py314haa95532_0
  - requests=2.32.5=py314haa95532_1
  - requests-toolbelt=1.0.0=py314haa95532_0
  - rpds-py=0.28.0=py314h114bc41_0
  - six=1.17.0=py314haa95532_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=hcdb6601_0
  - soupsieve=2.5=py314haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - streamlit=1.52.1=pyhd8ed1ab_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=1.1.0=py314haa95532_0
  - tornado=6.5.1=py314h827c3e9_0
  - typing-extensions=4.15.0=py314haa95532_0
  - typing_extensions=4.15.0=py314haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.0=py314haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vadersentiment=3.3.2=pyhd8ed1ab_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py314haa95532_0
  - webencodings=0.5.1=py314haa95532_2
  - win_inet_pton=1.1.0=py314haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yfinance=0.2.57=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - gdeltdoc==1.12.0
prefix: C:\Users\LENOVO\anaconda3\envs\stockx
